spring.application.name=API-gateway
server.port=9000
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-twctg5mxoooke8y4.eu.auth0.com/
spring.security.oauth2.resourceserver.jwt.audience=https://dentalclinicbackend.api
logging.level.org.springframework.security=DEBUG
logging.level.com.netflix.discovery=DEBUG
logging.level.org.springframework.cloud=DEBUG
logging.level.root=INFO
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

### Clinic Service Route
#spring.cloud.gateway.routes[0].id=clinic-service
#spring.cloud.gateway.routes[0].uri=http://clinic-service:8080
#spring.cloud.gateway.routes[0].predicates[0]=Path=/api/clinic/**
### Appointment Service Route
#spring.cloud.gateway.routes[1].id=appointment-service
#spring.cloud.gateway.routes[1].uri=http://appointment-service:8081
#spring.cloud.gateway.routes[1].predicates[0]=Path=/api/appointment/**
### User Service Route
#spring.cloud.gateway.routes[2].id=user-service
#spring.cloud.gateway.routes[2].uri=http://user-service:8082
#spring.cloud.gateway.routes[2].predicates[0]=Path=/api/user/**