spring.application.name=user-service
server.port=8082
spring.security.oauth2.resourceserver.jwt.issuer-uri=dev-twctg5mxoooke8y4.eu.auth0.com
spring.security.oauth2.resourceserver.jwt.audience=https:/dentalclinicbackend.api
spring.data.mongodb.uri=mongodb+srv://admin:AsdaAsda@dentists.nlb2knf.mongodb.net/dentists
